name: TitleArea
version: ${project.version}
main: mrstraw.titlearea.TitleArea
api-version: 1.13
authors: [MrStraw]
description: Title in specific place
website: flugnu.xyz

commands:
  TitleArea:
    description: Access the TitleArea plugin's commands
    aliases: ta