name: TitleArea
version: ${project.version}
main: mrstraw.titlearea.TitleArea
api-version: 1.13
authors: [MrStraw]
description: Title in specific place
website: flugnu.xyz

commands:
  TitleArea:
    description: Create point that indicate when you look at them and enter them.
    aliases: ta